### ISSUE TITLE
packages for random forests

### ISSUE THREAD

**Issue by dashaub** [bsouhaib/BusinessAnalytics#1]
This looks like a really great course covering many of the themes and models used in data science and business analytics. As a suggestion, considering using the "Rborist" and "ranger" packages instead of "randomForest". These two packages are optimized for very long and wide data, respectively, and can process data much faster and handle factors with many levels better than the "randomForest" package. Both packages are also maintained and developing quickly. A somewhat outdated description and benchmark of the packages can be found here: https://arxiv.org/abs/1508.04409

**Comment by bsouhaib** [comment]
Thanks David. We will take that into account in the class.

Souhaib.

----------------------------------------------
Dr. Souhaib Ben Taieb
Monash University - Australia
www.ben-taieb.com <http://www.souhaib-bentaieb.com/>


2016-06-29 6:10 GMT+10:00 David Shaub <notifications@github.com>:
